[ ca ]
default_ca      = CA_default

[ CA_default ]
dir             = ./ca
database        = $dir/index.txt
serial          = $dir/serial.txt       # The current serial number in hex
private_key     = $dir/ca.key
certificate     = $dir/ca.crt
new_certs_dir   = $dir/certs

default_days    = 365                   # certificate validity days
default_md      = default               # message digest algo - use public key default
preserve        = no                    # preserve request DN order instead of policy order
unique_subject  = no                    # issue certs with same subject
policy          = subject_policy

# Certificate Revocation List (CRL) options
crlnumber       = $dir/crlnumber.txt    # the current CRL update number
crl_extensions  = crl_ext
default_crl_days= 1                     # how long before next CRL update

# Certificate display options
name_opt        = ca_default            # Subject name display options
cert_opt        = ca_default            # Certificate fields display options

[ subject_policy ]
countryName             = match         # Match CA countryName
stateOrProvinceName     = optional
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied      # Not optional
emailAddress            = optional

[ ca_crt ]
basicConstraints = critical,CA:true
keyUsage = critical,keyCertSign,cRLSign

[ crl_ext ]
authorityKeyIdentifier=keyid:always
